import { z } from "zod";

const booleanFromNumber = z.number().transform((val) => Boolean(val));

export const SpellSchema = z.object({
    id: z.number(),
    name: z.string(),
    school: z.string(),
    subschool: z.string(),
    descriptor: z.string(),
    spell_level: z.string(),
    casting_time: z.string(),
    components: z.string(),
    costly_components: booleanFromNumber,
    range: z.string(),
    area: z.string(),
    effect: z.string(),
    targets: z.string(),
    duration: z.string(),
    dismissible: booleanFromNumber,
    shapeable: booleanFromNumber,
    saving_throw: z.string(),
    spell_resistance: z.string(),
    description: z.string(),
    description_formatted: z.string(),
    source: z.string(),
    full_text: z.string(),
    verbal: booleanFromNumber,
    somatic: booleanFromNumber,
    material: booleanFromNumber,
    focus: booleanFromNumber,
    divine_focus: booleanFromNumber,
    sor: z.number().nullable(),
    wiz: z.number().nullable(),
    cleric: z.number().nullable(),
    druid: z.number().nullable(),
    ranger: z.number().nullable(),
    bard: z.number().nullable(),
    paladin: z.number().nullable(),
    alchemist: z.number().nullable(),
    summoner: z.number().nullable(),
    witch: z.number().nullable(),
    inquisitor: z.number().nullable(),
    oracle: z.number().nullable(),
    antipaladin: z.number().nullable(),
    magus: z.number().nullable(),
    adept: z.number().nullable(),
    bloodrager: z.number().nullable(),
    shaman: z.number().nullable(),
    psychic: z.number().nullable(),
    medium: z.number().nullable(),
    mesmerist: z.number().nullable(),
    occultist: z.number().nullable(),
    spiritualist: z.number().nullable(),
    skald: z.number().nullable(),
    investigator: z.number().nullable(),
    hunter: z.number().nullable(),
    summoner_unchained: z.number().nullable(),
    deity: z.string(),
    SLA_level: z.number().nullable(),
    domain: z.string(),
    short_description: z.string(),
    acid: booleanFromNumber,
    chaotic: booleanFromNumber,
    cold: booleanFromNumber,
    curse: booleanFromNumber,
    darkness: booleanFromNumber,
    death: booleanFromNumber,
    disease: booleanFromNumber,
    earth: booleanFromNumber,
    electricity: booleanFromNumber,
    emotion: booleanFromNumber,
    evil: booleanFromNumber,
    fear: booleanFromNumber,
    fire: booleanFromNumber,
    force: booleanFromNumber,
    good: booleanFromNumber,
    language_dependent: booleanFromNumber,
    lawful: booleanFromNumber,
    light: booleanFromNumber,
    mind_affecting: booleanFromNumber,
    pain: booleanFromNumber,
    shadow: booleanFromNumber,
    sonic: booleanFromNumber,
    water: booleanFromNumber,
    ruse: booleanFromNumber,
    draconic: booleanFromNumber,
    meditative: booleanFromNumber,
    mythic: booleanFromNumber,
    linktext: z.string(),
    material_costs: z.number().nullable(),
    bloodline: z.string(),
    patron: z.string(),
    mythic_text: z.string(),
    augmented: z.string(),
    haunt_statistics: z.string(),
});
export type Spell = z.infer<typeof SpellSchema>;
export const SpellArraySchema = z.array(SpellSchema);

export const ManifestSpellDetailSchema = z.object({
    name: z.string(),
    id: z.number(),
    short_description: z.string(),
    duration: z.string(),
    range: z.string(),
    saving_throw: z.string(),
    spell_resistance: z.string(),
    casting_time: z.string(),
    sor: z.number().nullable(),
    wiz: z.number().nullable(),
    cleric: z.number().nullable(),
    druid: z.number().nullable(),
    ranger: z.number().nullable(),
    bard: z.number().nullable(),
    paladin: z.number().nullable(),
    alchemist: z.number().nullable(),
    summoner: z.number().nullable(),
    witch: z.number().nullable(),
    inquisitor: z.number().nullable(),
    oracle: z.number().nullable(),
    antipaladin: z.number().nullable(),
    magus: z.number().nullable(),
    adept: z.number().nullable(),
    bloodrager: z.number().nullable(),
    shaman: z.number().nullable(),
    psychic: z.number().nullable(),
    medium: z.number().nullable(),
    mesmerist: z.number().nullable(),
    occultist: z.number().nullable(),
    spiritualist: z.number().nullable(),
    skald: z.number().nullable(),
    investigator: z.number().nullable(),
    hunter: z.number().nullable(),
    summoner_unchained: z.number().nullable(),
});
export type ManifestSpellDetail = z.infer<typeof ManifestSpellDetailSchema>;
export const ManifestSpellDetailArraySchema = z.array(
    ManifestSpellDetailSchema
);
