export type Spell = {
    name: string;
    school: string;
    subschool: string | null;
    descriptor: string | null;
    spell_level: string;
    casting_time: string;
    components: string;
    costly_components: boolean;
    range: string;
    area: string | null;
    effect: string | null;
    targets: string | null;
    duration: string;
    dismissible: boolean;
    shapeable: boolean;
    saving_throw: string | null;
    spell_resistance: string | null;
    description: string | null;
    description_formatted: string | null;
    source: string | null;
    full_text: string | null;
    verbal: boolean;
    somatic: boolean;
    material: boolean;
    focus: boolean;
    divine_focus: boolean;
    sor: number | null;
    wiz: number | null;
    cleric: number | null;
    druid: number | null;
    ranger: number | null;
    bard: number | null;
    paladin: number | null;
    alchemist: number | null;
    summoner: number | null;
    witch: number | null;
    inquisitor: number | null;
    oracle: number | null;
    antipaladin: number | null;
    magus: number | null;
    adept: number | null;
    bloodrager: number | null;
    shaman: number | null;
    psychic: number | null;
    medium: number | null;
    mesmerist: number | null;
    occultist: number | null;
    spiritualist: number | null;
    skald: number | null;
    investigator: number | null;
    hunter: number | null;
    summoner_unchained: number | null;
    deity: string | null;
    SLA_Level: number | null;
    domain: string | null;
    short_description: string | null;
    acid: boolean;
    chaotic: boolean;
    cold: boolean;
    curse: boolean;
    darkness: boolean;
    death: boolean;
    disease: boolean;
    earth: boolean;
    electricity: boolean;
    emotion: boolean;
    evil: boolean;
    fear: boolean;
    fire: boolean;
    force: boolean;
    good: boolean;
    language_dependent: boolean;
    lawful: boolean;
    light: boolean;
    mind_affecting: boolean;
    pain: boolean;
    shadow: boolean;
    sonic: boolean;
    water: boolean;
    ruse: boolean;
    draconic: boolean;
    meditative: boolean;
    mythic: boolean;
    linktext: string | null;
    material_costs: number | null;
    bloodline: string | null;
    patron: string | null;
    mythic_text: string | null;
    augmented: string | null;
    haunt_statistics: string | null;
};

export type StringTuple = [string, ...string[]];
