export type Spell = {
    name: string;
    school: string;
    subschool: string | null;
    descriptor: string | null;
    spell_level: string;
    casting_time: string;
    components: string;
    costly_components: boolean;
    range: string;
    area: string | null;
    effect: string | null;
    targets: string | null;
    duration: string;
    dismissible: boolean;
    shapeable: boolean;
    saving_throw: string | null;
    spell_resistance: string | null;
    description: string | null;
    description_formatted: string | null;
    source: string | null;
    full_text: string | null;
    verbal: boolean;
    somatic: boolean;
    material: boolean;
    focus: boolean;
    divine_focus: boolean;
    sor: number | null;
    wiz: number | null;
    cleric: number | null;
    druid: number | null;
    ranger: number | null;
    bard: number | null;
    paladin: number | null;
    alchemist: number | null;
    summoner: number | null;
    witch: number | null;
    inquisitor: number | null;
    oracle: number | null;
    antipaladin: number | null;
    magus: number | null;
    adept: number | null;
    bloodrager: number | null;
    shaman: number | null;
    psychic: number | null;
    medium: number | null;
    mesmerist: number | null;
    occultist: number | null;
    spiritualist: number | null;
    skald: number | null;
    investigator: number | null;
    hunter: number | null;
    summoner_unchained: number | null;
    deity: string | null;
    SLA_Level: number | null;
    domain: string | null;
    short_description: string | null;
    acid: boolean;
    chaotic: boolean;
    cold: boolean;
    curse: boolean;
    darkness: boolean;
    death: boolean;
    disease: boolean;
    earth: boolean;
    electricity: boolean;
    emotion: boolean;
    evil: boolean;
    fear: boolean;
    fire: boolean;
    force: boolean;
    good: boolean;
    language_dependent: boolean;
    lawful: boolean;
    light: boolean;
    mind_affecting: boolean;
    pain: boolean;
    shadow: boolean;
    sonic: boolean;
    water: boolean;
    ruse: boolean;
    draconic: boolean;
    meditative: boolean;
    mythic: boolean;
    linktext: string | null;
    material_costs: number | null;
    bloodline: string | null;
    patron: string | null;
    mythic_text: string | null;
    augmented: string | null;
    haunt_statistics: string | null;
};

export type SpellFromCSV = {
    name: string;
    school: string;
    subschool: string;
    descriptor: string;
    spell_level: string;
    casting_time: string;
    components: string;
    costly_components: string;
    range: string;
    area: string;
    effect: string;
    targets: string;
    duration: string;
    dismissible: string;
    shapeable: string;
    saving_throw: string;
    spell_resistance: string;
    description: string;
    description_formatted: string;
    source: string;
    full_text: string;
    verbal: string;
    somatic: string;
    material: string;
    focus: string;
    divine_focus: string;
    sor: string;
    wiz: string;
    cleric: string;
    druid: string;
    ranger: string;
    bard: string;
    paladin: string;
    alchemist: string;
    summoner: string;
    witch: string;
    inquisitor: string;
    oracle: string;
    antipaladin: string;
    magus: string;
    adept: string;
    bloodrager: string;
    shaman: string;
    psychic: string;
    medium: string;
    mesmerist: string;
    occultist: string;
    spiritualist: string;
    skald: string;
    investigator: string;
    hunter: string;
    summoner_unchained: string;
    deity: string;
    SLA_Level: string;
    domain: string;
    short_description: string;
    acid: string;
    chaotic: string;
    cold: string;
    curse: string;
    darkness: string;
    death: string;
    disease: string;
    earth: string;
    electricity: string;
    emotion: string;
    evil: string;
    fear: string;
    fire: string;
    force: string;
    good: string;
    language_dependent: string;
    lawful: string;
    light: string;
    mind_affecting: string;
    pain: string;
    shadow: string;
    sonic: string;
    water: string;
    ruse: string;
    draconic: string;
    meditative: string;
    mythic: string;
    linktext: string;
    material_costs: string;
    bloodline: string;
    patron: string;
    mythic_text: string;
    augmented: string;
    haunt_statistics: string;
};

export type SpellWithOnlyName = {
    name: string;
};

export type StringTuple = [string, ...string[]];
