name: spellbook-backend

services:
    spellbook-api-server:
        build:
            context: .
            target: development
        image: spellbook-api-server
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src

    spellbook-postgres-database:
        image: postgres:17.3
        environment:
            POSTGRES_PASSWORD: password
