-- Setup the database structure and tables


-- Create table for the d20pfsrd data.
CREATE TABLE IF NOT EXISTS d20pfsrd (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    school TEXT NOT NULL,
    subschool TEXT,
    descriptor TEXT,
    spell_level TEXT NOT NULL,
    casting_time TEXT NOT NULL,
    components TEXT NOT NULL,
    costly_components BOOLEAN NOT NULL CHECK (cost_components IN (0, 1)),
    range TEXT NOT NULL,
    area TEXT,
    effect TEXT,
    targets TEXT,
    duration TEXT NOT NULL,
    dismissible,
    shapeable,
    saving_throw,
    spell_resistance,
    description,
    description_formatted,
    source,
    full_text,
    verbal,
    somatic,
    material,
    focus,
    divine_focus,
    sor,
    wiz,
    cleric,
    druid,
    ranger,
    bard,
    paladin,
    alchemist,
    summoner,
    witch,
    inquisitor,
    oracle,
    antipaladin,
    magus,
    adept,
    deity,
    SLA_level,
    domain,
    short_description,
    acid,
    chaotic,
    cold,
    curse,
    darkness,
    death,
    disease,
    earth,
    electricity,
    emotion,
    evil,
    fear,
    fire,
    force,
    good,
    language_dependent,
    lawful,
    light,
    mind_affecting,
    pain,
    shadow,
    sonic,
    water,
    linktext,
    material_costs,
    bloodline,
    patron,
    mythic_text,
    augmented,
    mythic,
    bloodrager,
    shaman,
    psychic,
    medium,
    mesmerist,
    occultist,
    spiritualist,
    skald,
    investigator,
    hunter,
    haunt_statistics,
    ruse,
    draconic,
    meditative,
    summoner_unchained
)